### ISSUE TITLE
Add new IP's to config.berlin.freifunk.net

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/ansible#25]
https://github.com/freifunk/icvpn-meta/pull/623 has been merged.  We now have more IP addresses.

10.248.0.0/14

**Comment by rtznprmpftl** [comment]
@pmelange as far as i understand we need to add it to the nipap pool 'Mesh IPv4' . Or?

**Comment by pmelange** [comment]
At one point in time @booo and I were able to have the wizard use both the API_POOL_MESH and API_POOL_HNA to pull addresses.  This is because the HNA pool was completely exhausted and the MESH pool was more-or-less unused.  I don't remember what we had to change though.  But I think that if we can have all IP addresses in one pool and to give out the addresses, whether for DHCP (HNA) or MESH, then we will be fine.

**Comment by pmelange** [comment]
Ok, so I booted the old VM.  We set the variables API_POOL_MESH and API_POOL_HNA both to "Mesh IPv4'.  We didn't combine the pools.

So yeah, I would suggest putting them in "Mesh IPv4" and probably we should change the code to only take IP addresses from the Mesh IPv4 pool and no longer from the HNA pool.

**Comment by pmelange** [comment]
Hehe, I just took a look and both those variables are already set in the config.  So all looks ready to go.

But maybe we should move all IP's from the old HNA pool also into the Mesh pool so we can still use them.

**Comment by Akira25** [comment]
@pmelange  Do you feel comfortable with handling in a PR for that in https://github.com/freifunk-berlin/config.berlin.freifunk.net? As far as I understand, the app is still pulled from there.

If you don't want to do that, maybe @rtznprmpftl is the one with the most expertise on that field currently.

**Comment by Akira25** [comment]
I added the prefix via nipap-cli. I have no Idea, how we can include that into ansible in the current state.
Before:
```
root@config:/home/martin# nipap pool view "Mesh IPv4"
-- Pool 
  ID                         : 4
  Name                       : Mesh IPv4
  Description                : 
  Default type               : assignment
  Implied VRF RT / name      : None / default
  Preflen (v4/v6)            : 32 / None
-- Extra Attributes
-- Tags
-- Statistics
  IPv4 prefixes Used / Free  : 9768 / 22568 (30.21% of 32336)
  IPv6 prefixes Used / Free  : N/A (No IPv6 member prefixes)
  IPv4 addresses Used / Free : 43560 / 22488 (65.95% of 66048)
  IPv6 addresses Used / Free  : N/A (No IPv6 member prefixes)

-- Prefixes in pool - v4: 2  v6: 0
  10.31.0.0/16
  10.31.16.0/23
  ```

After:
```
root@config:/home/martin# nipap pool view "Mesh IPv4"
-- Pool 
  ID                         : 4
  Name                       : Mesh IPv4
  Description                : 
  Default type               : assignment
  Implied VRF RT / name      : None / default
  Preflen (v4/v6)            : 32 / None
-- Extra Attributes
-- Tags
-- Statistics
  IPv4 prefixes Used / Free  : 9768 / 284712 (3.32% of 294480)
  IPv6 prefixes Used / Free  : N/A (No IPv6 member prefixes)
  IPv4 addresses Used / Free : 43560 / 284632 (13.27% of 328192)
  IPv6 addresses Used / Free  : N/A (No IPv6 member prefixes)

-- Prefixes in pool - v4: 3  v6: 0
  10.31.0.0/16
  10.31.16.0/23
  10.248.0.0/14
  ```

**Comment by Akira25** [comment]
So I think, we can close this ticket for now. Feel free to reopen, if there is anything I've missed.
